MetricsDAO/xyz

index.html

* Updates 'Partner With Us' link in the navigation bar to link directly to the form instead of scrolling down.
* Updates 'Learn More About The Metric Token' button to use the proper link as it was redirecting to the form instead of the whitepaper.

Fixing 'Partner with Us' buttons / links.

---

app/routes/showcase/index.jsx

fix (showcase) @ #14: updating margin styles to optimize mobile ui

---

app/components/landing-header.tsx

Fix Discord link

---

app/entry.client.tsx
app/routes/showcase/Comments.jsx
app/routes/showcase/index.jsx

Add - Reviewers reviews and scores for submissions

---

.prettierrc
eslintrc.js

prettier formatting updates

---

app/components/AllQuestionsByState.tsx
app/components/AllQuestionsContainer.tsx
app/components/CreateQuestionContainer.tsx
app/components/PaginatedItems.tsx
app/components/QuestionControls.tsx
app/components/RewardsHeader.tsx
app/components/SelectWallet.tsx
app/components/ShowMetric.tsx
app/components/ShowQuestions.tsx
app/components/ShowUser.tsx
app/components/WalletProvider.tsx
app/components/Wrapper.tsx
package-lock.json
package.json
patches/@remix-run+dev+1.7.0.patch
patches/safe-event-emitter+1.0.1.patch
protocol-scripts/allocationAssigner.js

I was able to get wagmi up to the latest version with no dependency conflicts on my end, as well as getting the Coinbase Wallet Connector working properly. I wish the amount of work I put into the Coinbase issue was worth more than just not having to use the injected browser wallet button but hey we're here now. The coinbase issue, and I believe some of the issues with react-query were caused by some weird nuance within remix, which was remedied with the two patches recommended by wagmi in the base dir folder. I added the patches to the post install so everything should work smoothly in production and dev environments post merge.
All wagmi usage I could find was migrated to the new migrated methods. There are some of the still WIP components that might have been overlooked, so a test …

Wagmi Migration & Coinbase Wallet Connection

---

app/components/NetworkRender.tsx
app/components/RewardsHeader.tsx
app/components/Wrapper.tsx

switch network bugfix for hardhat and polygon

use different chain for primary object

---

.prettierrc

Updates to prettier file with defaults so if people override locally it will always go to default

update prettier settings file

---

app/components/SocialIcons.tsx
app/components/landing-header.tsx

Users were finding it unclear how to get to our discord. This should add the link to social links and more clarity to the "Join" button.

Add discord links and icons to make it more clear for users

---

README.md
package.json
remix.config.js

+ `yarn run prod` for running prod build of the app (for troubleshooting)
+ `yarn` for everything in package.json

Tailwind+Mantine README. 

---

app/components/AppHeader.tsx
app/components/ConnectButton.tsx
app/components/Shell.tsx

Our previous header was not super responsive and flexible. Updating to use a Mantine header to keep things consistent and responsive.

update to a mantine responsive header

---

app/components/CountDown.tsx
app/components/CountDownCard.tsx
app/routes/app/brainstorm/$marketplace.challenges.tsx
app/routes/app/brainstorm/c/$id.claim.tsx
app/routes/app/brainstorm/c/$id.review.tsx
app/routes/app/brainstorm/c/$id.tsx
app/utils/use-update-interval.ts
yarn.lock

Dev to Main

---

app/components/AppHeader.tsx
app/routes/app/brainstorm/$id.challenges.tsx
app/routes/app/brainstorm/c/$id.review.tsx
app/routes/app/brainstorm/c/$id.submit.tsx
app/routes/app/brainstorm/c/$id/participants.tsx
app/routes/app/brainstorm/s/$id.tsx
app/routes/app/rewards/index.tsx

Making things closer to designs

Updates based on feedback

---

app/features/shell/shell.tsx

Background was getting cut off at the bottom and overflowing horizontally.

fix: bg blur div overflow

---

app/components/avatar/avatar.tsx
app/components/avatar/token-avatar.tsx
app/components/select/select.tsx
app/domain/labor-market.ts
app/features/add-payment-address-form.tsx
app/routes/app/rewards/addresses.tsx

Add address component

---

app/routes/api/verify.ts
package.json
yarn.lock

Same as previous, resubmit for easier resolving

Replace Web3.js in the backend with ethers.js

---

app/env.ts

We can just use zod for validating the env.

refactor: use zod for env

---

app/routes/app/$type/index.tsx
app/routes/app/$type/m/$laborMarketAddress/index.tsx
app/utils/fakes.ts
prisma/seed.ts

fix: service requests loader on labor market details page

---

app/features/marketing-shell/footer.tsx
app/routes/__marketing/index.tsx
app/routes/__marketing/partner.tsx

Partner with Us page feedback

---

app/components/countdown-card/countdown-card.tsx
app/components/countdown/countdown.tsx
app/hooks/use-countdown.tsx
app/utils/date.ts
app/utils/helpers.ts

fix: negative countdowns

---

app/components/user-badge/user-badge.tsx
app/features/rpc-error.tsx
app/features/web3-button/approve-erc20-transfer.tsx
app/features/web3-button/claim-reward.tsx
app/features/web3-button/claim-to-review.tsx
app/features/web3-button/claim-to-submit.tsx
app/features/web3-button/create-labor-market.tsx
app/features/web3-button/create-service-request.tsx
app/features/web3-button/create-submission.tsx
app/features/web3-button/review-submission.tsx
app/features/web3-button/types.ts
app/hooks/use-approve-erc20.ts
app/hooks/use-claim-reward.ts
app/hooks/use-claim-to-review.ts
app/hooks/use-claim-to-submit.ts
app/hooks/use-create-labor-market.ts
app/hooks/use-create-service-request.tsx
app/hooks/use-create-submission.ts
app/hooks/use-review-submission.ts
app/routes/app/$mType/m/$laborMarketAddress.s/$submissionId.tsx
app/routes/app/$mType/m/$laborMarketAddress.sr/$serviceRequestId.claim.tsx
app/routes/app/$mType/m/$laborMarketAddress.sr/$serviceRequestId.review.tsx
app/routes/app/$mType/m/$laborMarketAddress.sr/$serviceRequestId.submit.tsx
app/routes/app/$mType/m/$laborMarketAddress.sr/$serviceRequestId.tsx
app/routes/app/$mType/m/$laborMarketAddress.sr/new.tsx
app/routes/app/$mType/new.tsx

Error handling on prepare contract writes

---

app/routes/__marketing/partner.tsx

Remove data readiness

---

app/domain/labor-market.ts
app/domain/submission.ts
app/features/challenge-form.tsx
app/hooks/use-claim-reward.ts
app/hooks/use-create-labor-market.ts
app/hooks/use-has-performed.ts
app/services/labor-market.server.ts
app/services/submissions.server.ts
indexer/worker.ts
package.json
pinekit/cli.ts
yarn.lock

labor-markets-abi 1.60

---

app/features/permission-icon.tsx
app/routes/app+/market.$address.prereqs.tsx
app/routes/app+/market_.$address.request.$requestId.prereqs.tsx

Red x for prereqs

---

app/features/challenge-pool-badges.tsx
app/features/marketplaces-list-view.tsx
app/routes/app+/iou-center.index.tsx
app/routes/app+/market.$address.index.tsx
app/routes/app+/rewards.addresses.tsx
app/routes/app+/rewards.index.tsx

plus standardizing all the table header text styling

Challenge pool Badges expand on hover

---

app/features/web3-button/approve-erc20-transfer.tsx
app/features/web3-button/claim-reward.tsx

fix: metamask confirm twice

---

app/domain/service-request.test.ts
app/domain/service-request.ts

add error handling for deadlines

---

app/domain/labor-market/schemas.ts
app/routes/app+/$mType.tsx
app/services/service-request.server.ts

Resolves #492 
Resolves #493
Resolves #497

fix: service request related bugs

---

app/components/tx-modal/tx-modal.tsx
app/features/claim-to-submit-creator/claim-to-submit-creator.tsx
app/routes/app+/market_.$address.request_.$requestId.claim.tsx

Confusingly, accidentally already committed `claim-to-submit-creator.tsx` in previous PR

claim to submit tx flow refactor

---

app/domain/submission/schemas.ts
app/features/marketplaces-list-view.tsx
app/routes/app+/challenges.tsx
app/routes/app+/market_.$address.request.$requestId.index.tsx
app/routes/app+/market_.$address.submission.$submissionId.tsx

* bad boolean logic on permission filters
* createdAtBlocktimestamp mismap
* Score of 0 truthiness check

bug fixes with recent merges

---

app/features/challenges/list-challenges/list-challenges.tsx
app/features/claim-to-review-creator/claim-to-review-creator.tsx
app/routes/app+/market.$address.index.tsx
app/routes/app+/market_.$address.request.$requestId.tsx
app/routes/app+/market_.$address.request_.$requestId.claim.tsx

Revert "Challenge page has different breadcrumbs"

---

app/routes/api+/market.$address.submission.$id.ts

For treasury team to extract enforcement expiration date

Endpoint to get submission and service request data

---

app/components/gating-badge/gating-badge.tsx
app/components/gating-badge/index.ts
app/components/index.ts
app/domain/labor-market/schemas.ts
app/features/labor-market-creator/labor-market-creator.tsx
app/features/labor-market-creator/schema.ts
app/features/service-request-creator/analyst-form.tsx
app/hooks/use-token-data.ts
app/routes/app+/market.$address.prereqs.tsx
app/routes/app+/market_.$address.request.$requestId.prereqs.tsx
app/utils/helpers.ts

labor market prereqs UI cards

---

app/features/service-request-creator/analyst-form.tsx
app/routes/app+/market_.$address.request.new.analyst.tsx

- doesn't hardcode analyst curve type

Small fix - don't hardcode curve type

---

app/domain/submission/index.server.ts
app/features/labor-market-creator/labor-market-creator.tsx
app/features/service-request-creator/service-request-creator.tsx
app/features/submission-creator/submission-creator.tsx
app/routes/api+/index-event.ts
app/services/mongo.server.ts
app/utils/helpers.ts

Revert "790 v2 migration create submission redirect"

---

app/features/service-request-creator/analyst-form.tsx
app/features/service-request-creator/overview-form.tsx
app/features/service-request-creator/reviewer-form.tsx
app/features/service-request-creator/schema.test.ts
app/features/service-request-creator/schema.ts
app/features/service-request-creator/service-request-creator.tsx
app/routes/app+/market_.$address.request.$requestId.rewards.tsx

- standardized and made accurate
- reward curve chart accurate input (challenges page)
- todo: correct bignumber math

Analyst and Reviewer Reward pools

---

app/abi/iou-factory.ts
app/abi/iou-token.ts
app/components/gating-badge/gating-badge.tsx
app/domain/treasury.ts
app/features/iou-creator/iou-creator.tsx
app/features/iou-creator/schema.ts
app/features/iou-issue-token-creator.tsx
app/features/labor-market-creator/overview-form.tsx
app/features/labor-market-creator/reward-curve-constants.tsx
app/features/reward-review-creator/reward-review-iou-creator.tsx
app/features/reward-submission-creator/reward-submission-iou-creator.tsx
app/features/service-request-creator/service-request-creator.tsx
app/features/token-creator/schema.ts
app/features/token-creator/token-creator.tsx
app/routes/api+/add-iou-token.tsx
app/routes/api+/add-token.tsx
app/routes/app+/iou-center.index.tsx
app/routes/app+/iou-center.tsx
app/services/tokens.server.ts
app/services/treasury.server.ts
app/utils/fetch.ts

dev->main: Iou center feature branch (#895)

---

app/domain/labor-market/functions.server.ts
app/domain/labor-market/schemas.ts
app/domain/service-request/functions.server.ts
app/domain/service-request/schemas.ts
app/routes/app+/analyze.tsx
app/routes/app+/challenges.tsx
app/utils/constants.ts

Reverts MetricsDAO/xyz#921
No longer need to hide this labor market anymore

Revert "blacklist for hiding labor markets and challenges"

---

app/utils/pine-config.server.ts

reindex (#934)

---

.github/workflows/deploy.yml
app/contexts/wallet-provider.tsx
app/utils/pine-config.server.ts
app/wagmi.ts
fly.toml
package.json
yarn.lock

- moves the protocol from v2.1.0 to v2.2.0

feat: update prod package to 2.2.0
